shadow = false;
fading = false;
inactive-dim = 0.1;
backend = "glx";
glx-no-stencil = true;
vsync = true;
mark-ovredir-focused = false;
refresh-rate = 60;
detect-client-leader = true;
log-level = "warn";
focus-exclude = "x = 0 && y = 0 && override_redirect = true";
